spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1
      ack-mode: manual_immediate
    producer:
      topic: metrics
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: 1
    consumer:
      groupId: test-group-2
      auto-offset-reset: earliest
      topic: metrics
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'com.shvets.kafkaandcouchbase.kafka.model'

bootstrap:
  count: 10
  sender-type: async


storage:
  host: "couchbase://127.0.0.1"
  bucket: IOT
  username: Administrator
  password: 123456
  expiry: 0

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

